### ISSUE TITLE
Problem with using of overpass css from openshift

### ISSUE THREAD

**Issue by mignev** [openshift/oo-index#32]
Hello guys,
i saw that there are some problems with using of this css: <link rel="stylesheet" href="https://openshift.redhat.com/app/assets-20131211170319/overpass.css"/> in `wsgi / templates / layout.html`.

The problem are following:
1. In the css file itself the paths are in this way `/app/assets....` which means this doesn't work on oo-index because the browser looks in `http://oo-index.instalation.com/app/assets....` and in the current oo-index installation there isn't that directroy with these files because we load them remotely. So we have to find any other way to use this file if this is important.
2. The second problem is with the name of the directory `assets-<timestamp>`. When the openshift web team deploys new release of the web and update the theirs assets the name of the directory will be change. So again we have to find any other way of using it it this is important.

**Comment by caruccio** [comment]
Hi @mignev.
In fact those files are there because the old code base added them (think it was already a 404 back then), and I tried to not mess with old stuff.
This code needs a real cleanup. In case you didn't noticed, we are using a single bundle.js which I did by cat()ing all .js files :-)

Unfortunately I won't be able to work on this project this week. Please feel free to make any changes you think are needed - I saw you PEP8'ed one file already :+1: 

Welcome to OO-Index!

**Comment by mignev** [comment]
Hi @caruccio,
thank you very much for the welcoming! I love to help in every way to projects with open idea! So for me is so fun to do that! :)

In case of the messy code I think that is more than normal. Because every first version of everything that we are doing is proof of concept ... and the hacking is so fun at all :) Actually you've done a very good job! Respect!

In case of code changes, I will see what can I do.

Thanks once again for the welcoming. You rockz guys!
