### ISSUE TITLE
Initial git url and timeouts

### ISSUE THREAD

**Issue by caruccio** [openshift/oo-index#8]
Today there is a timeout when creating an app (don't remember how long it is right now).

This limit may be reached either by using a big repository as your "--form-code/Source Code" or by a too long compilation time.

Today the solution is to instruct users to first create the app, clone it locally, merge with quickstart, and then, push it to OO.

IMHO, this is a far from ideal approach.

How could we address it?

**Comment by dmueller2001** [comment]
Today, the prototype simply launches the origin-console and  'fills' in the fields on the origin-console. This leaves all the management and messaging of timeouts etc to the origin-console. This is the MVP is meant to the index for Discovery of QuickStarts & Cartridges, the "launch" functionality is simply a hand-off in the proto-type. The time out limitation is set by the PaaS itself and not something the developer has control over; each PaaS administrator 'sets' the timeout - and I believe it is a configuration time setting.

I would say this is "out-of-scope" for this MVP iteration of the oo-index. 

Thoughts?

**Comment by ryanj** [comment]
I think there is a trello card for addressing the timeout issue in the upstream code.  Does anyone have a link that will help us track the progress on this item?
We should let them know that the issue is a potential blocker for this effort.

**Comment by dmueller2001** [comment]
ryanj, how is it a blocker for this oo-index project? as i see it, it's an origin console issue - as you are passing off control and leaving the oo-index app once you click on "Run On OpenShift"  button in the current prototype workflow. FYI: In the mock-ups, I have renamed this button to "Launch" 

I don't disagree that it is an issue but it does not fall into the scope of this effort and i don't see it as a blocker for discovery of the app.

**Comment by ryanj** [comment]
I think @namduong is already tracking the issue.  I'll check with him for an update.

I'm not sure if Nam's team uses the same terminology, but "it's a blocker for us" is usually just scrum slang for "we would like to escalate the priority of this issue and attach a due date, since we want to have it fixed before we make our launch announcement".

That's not really my call to make though.  You can announce whenever

**Comment by dmueller2001** [comment]
Ryan & Mateus - on second thought - I think that there might need to be a metadata tag in the json that flags quick starts as ones that will only be launch-able due to timeouts from rhc/command line. 

For example there is a couchdb quick start that works from the cmd line but takes hour(s) to build all it's dependencies. We would like to have it included but perhaps have some visual icon on the list that says 'rhc only'

**Comment by dmueller2001** [comment]
diane will add a metadata tag to json to flag if item can/should only be run from rhc and think about how to expose that in the UX; and revise mocks-ups

**Comment by ryanj** [comment]
Bug filed: https://bugzilla.redhat.com/show_bug.cgi?id=1062735
